backend:
  name: github
  repo: "Matt-BMaking/rxusa-us-code"
  branch: main
  base_url: "https://rxusa-us-code-auth.matthewberry0909.workers.dev"
  auth_endpoint: "/auth?provider=github"

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "code"
    label: "Code"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
